name: shepherd
description: Advanced CLI automation and productivity engine for Flutter/Dart. Simplifies developer workflows (clean, deploy, changelog) and bridges Design Systems to testing with Atomic Design and Maestro.
version: 0.8.1
homepage: https://shepherd.inatos.com.br	
repository: https://github.com/cruvinelrv/shepherd
documentation: https://shepherd.inatos.com.br/docs
license: MIT

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  sqflite_common_ffi: ^2.3.6
  path: ^1.9.1
  yaml: ^3.1.3
  yaml_writer: ^2.1.0
  args: ^2.7.0
  http: ^1.2.0
  shepherd_tag: ^0.0.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  mockito: any

executables:
  shepherd:
